services:
  - type: web
    name: api-utilisateur
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      DATABASE_URL: "TO_BE_FILLED"